# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ParseAnalytics' do
pod 'Parse'
end

target 'ParseAnalyticsTests' do

end

target 'ParseAnalyticsUITests' do

end

